databases:
  - name: laravel_db
    plan: free
    databaseName: laravel_db
    user: laravel_user

services:
  - type: web
    plan: free
    name: laravel-app
    runtime: docker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: laravel_db
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: WEBROOT
        value: /var/www/html/public
      - key: RUN_SCRIPTS
        value: 1
      - key: REAL_IP_HEADER
        value: 1
      - key: SKIP_COMPOSER
        value: 1
